name: Python testing

on:
  - pull_request
  - push

jobs:
  test:
    name: test python code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Test cloud-info-generator
      run: |
        pip install -r requirements.txt
        pip install .
        # this is as far as we get for now
        fedcloud-vm-monitor --help
