---
name: Python testing

on: [pull_request, push]

jobs:
  test:
    name: test python code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install package
        run: pip install .
      - name: Try to run the command
        run: |
          fedcloud-vo-monitor --help
